// destinations.js

const destinations = [
  "Mumbai, Maharashtra, India",
  "Paris, Île-de-France, France",
  "New York, New York, USA",
  "Tokyo, Tokyo Prefecture, Japan",
  "Sydney, New South Wales, Australia",
  "Toronto, Ontario, Canada",
  "Berlin, Berlin, Germany",
  "Cape Town, Western Cape, South Africa",
  "São Paulo, São Paulo, Brazil",
  "Dubai, Dubai, United Arab Emirates",
  "London, England, United Kingdom",
  "Singapore, Singapore, Singapore",
  "Los Angeles, California, USA",
  "Rome, Lazio, Italy",
  "Bangkok, Bangkok, Thailand",
  "Istanbul, Istanbul, Turkey",
  "Hong Kong, Hong Kong, China",
  "Mexico City, Mexico City, Mexico",
  "Moscow, Moscow Oblast, Russia",
  "Seoul, Seoul, South Korea",
  "Beijing, Beijing Municipality, China",
  "Buenos Aires, Buenos Aires, Argentina",
  "Lagos, Lagos, Nigeria",
  "Karachi, Sindh, Pakistan",
  "Jakarta, Jakarta, Indonesia",
  "Cairo, Cairo Governorate, Egypt",
  "Kuala Lumpur, Federal Territory, Malaysia",
  "Madrid, Madrid, Spain",
  "Lisbon, Lisbon, Portugal",
  "Amsterdam, North Holland, Netherlands",
  "Athens, Attica, Greece",
  "Vienna, Vienna, Austria",
  "Zurich, Zurich, Switzerland",
  "Barcelona, Catalonia, Spain",
  "Vancouver, British Columbia, Canada",
  "Chicago, Illinois, USA",
  "Miami, Florida, USA",
  "San Francisco, California, USA",
  "Rio de Janeiro, Rio de Janeiro, Brazil",
  "Santiago, Santiago Metropolitan Region, Chile",
  "Lima, Lima, Peru",
  "Bogotá, Bogota, Colombia",
  "Copenhagen, Capital Region, Denmark",
  "Stockholm, Stockholm County, Sweden",
  "Oslo, Oslo, Norway",
  "Helsinki, Uusimaa, Finland",
  "Warsaw, Masovian Voivodeship, Poland",
  "Prague, Prague, Czech Republic",
  "Budapest, Central Hungary, Hungary",
  "Brussels, Brussels, Belgium",
  "Dublin, Leinster, Ireland",
  "Edinburgh, Scotland, United Kingdom",
  "Manchester, England, United Kingdom",
  "Munich, Bavaria, Germany",
  "Frankfurt, Hesse, Germany",
  "Brisbane, Queensland, Australia",
  "Perth, Western Australia, Australia",
  "Melbourne, Victoria, Australia",
  "Auckland, Auckland, New Zealand",
  "Wellington, Wellington, New Zealand",
  "Havana, La Habana, Cuba",
  "Santo Domingo, Distrito Nacional, Dominican Republic",
  "Panama City, Panama, Panama",
  "San José, San José, Costa Rica",
  "San Salvador, San Salvador, El Salvador",
  "Guatemala City, Guatemala, Guatemala",
  "Manila, Metro Manila, Philippines",
  "Hanoi, Hanoi, Vietnam",
  "Ho Chi Minh City, Ho Chi Minh, Vietnam",
  "Kathmandu, Bagmati Province, Nepal",
  "Colombo, Western Province, Sri Lanka",
  "Dhaka, Dhaka, Bangladesh",
  "Islamabad, Islamabad Capital Territory, Pakistan",
  "Abu Dhabi, Abu Dhabi, United Arab Emirates",
  "Doha, Doha, Qatar",
  "Kuwait City, Al Asimah, Kuwait",
  "Muscat, Muscat, Oman",
  "Amman, Amman Governorate, Jordan",
  "Riyadh, Riyadh, Saudi Arabia",
  "Jeddah, Mecca, Saudi Arabia",
  "Jerusalem, Jerusalem District, Israel",
  "Tel Aviv, Tel Aviv District, Israel",
  "Baku, Baku, Azerbaijan",
  "Tbilisi, Tbilisi, Georgia",
  "Yerevan, Yerevan, Armenia",
  "Bishkek, Chuy Region, Kyrgyzstan",
  "Almaty, Almaty, Kazakhstan",
  "Tashkent, Tashkent, Uzbekistan",
  "Tehran, Tehran, Iran",
  "Baghdad, Baghdad, Iraq",
  "Beirut, Beirut Governorate, Lebanon",
  "Damascus, Damascus, Syria",
  "Casablanca, Casablanca-Settat, Morocco",
  "Rabat, Rabat-Salé-Kénitra, Morocco",
  "Tunis, Tunis, Tunisia",
  "Algiers, Algiers, Algeria",
  "Accra, Greater Accra, Ghana",
  "Nairobi, Nairobi, Kenya",
  "Addis Ababa, Addis Ababa, Ethiopia",
  "Dar es Salaam, Dar es Salaam, Tanzania",
  "Kinshasa, Kinshasa, Democratic Republic of the Congo",
  "Luanda, Luanda, Angola",
  "Maputo, Maputo, Mozambique",
  "Harare, Harare, Zimbabwe",
  "Antananarivo, Analamanga, Madagascar",
  "Windhoek, Khomas, Namibia",
  "Gaborone, South-East District, Botswana",
];

export default destinations;
